name: Linter file testing

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  python-linting-codes:
    name: python-linting-code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run Super-Linter
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
